[package]
name = "app"
type = "bin"
authors = [""]
compiler_version = ">=0.19.4"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.7", directory="yarn-project/aztec-nr/aztec" }
easy_private_state = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.7", directory="yarn-project/aztec-nr/easy-private-state" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.7", directory="yarn-project/aztec-nr/value-note"}
